### ISSUE TITLE
Compile with Linux Subsystem for the web

### ISSUE THREAD

**Issue by ghost** [cwoffenden/hello-webgpu#14]
Hello, Im using WSL with Emscripten and I just cant get it to compile. I ran
`cmake .`
`cmake --build .`
and it fails with fatal error: webgpu/webgpu.h: No such file or directory

**Comment by cwoffenden** [comment]
For Emscripten you need to use `emcmake`, for example:
```
emcmake cmake -B out/web -DCMAKE_BUILD_TYPE=Release
cmake --build out/web
```
I've not used Emscripten with WSL (only directly with Windows, Mac and Linux) but this should work.

**Comment by ghost** [comment]
That worked thanks. I am running now into the issue that Chrome throws the Error "No support for WebGPU; not starting" and shows nothing. I tried starting it via the command line (im running chrome on windows) with 
`chrome.exe --enable-unsafe-webgpu` and
`chrome.exe --enable-features=WebGPUService,WebGPU`
to no effect. 
These examples are running though: https://austin-eng.com/webgpu-samples

**Comment by cwoffenden** [comment]
I'm only maintaining compatibility with the latest version of the API (which is in flux whilst being finalised), so you'll need to use Chrome Canary for testing until Chrome catches up.

The samples in the link are written to work in older and newer versions of the spec.

**Comment by ghost** [comment]
Ok, installing Chrome Canary from https://www.google.com/chrome/canary/ and then enabling WebGPU under chrome://flags/#enable-unsafe-webgpu worked. Thanks a lot for you help!

**Comment by cwoffenden** [comment]
Eventually Chrome releases catch up with Canary and it'll just work.

(I'll add specific build instructions for Emscripten to the readme)
