### ISSUE TITLE
Compilation error and runtime error with emscripten 3.0.0

### ISSUE THREAD

**Issue by gracicot** [cwoffenden/hello-webgpu#15]
Hello! I have a problem running the webgpu example on a web page by compiling the code to wasm using the latest emscripten.

First, in `main.cpp` at line 345, 346, 347 and 348, I had to change `colorDesc.clearValue` to `colorDesc.clearColor`. It wouldn't compile otherwise.

Then after changing those line, running the example on chrome canary (`Version 104.0.5092.0 (Official Build) canary (x86_64)`).

The error is the following:

```
Uncaught TypeError: Failed to execute 'setVertexBuffer' on 'GPURenderPassEncoder': Value is outside the 'unsigned long long' value range.
```

<img width="945" alt="Screen Shot 2022-05-30 at 12 28 22 PM" src="https://user-images.githubusercontent.com/2906673/171031971-a72fd75e-1ce1-4f4d-8b5b-6198f01a4c2f.png">

The error look like it comes from the line 370:
```cpp
wgpuRenderPassEncoderSetVertexBuffer(pass, 0, vertBuf, 0, WGPU_WHOLE_SIZE);
```

The argument `WGPU_WHOLE_SIZE` seems to be transformed to `-4294967297` in the javascript side:

<img width="876" alt="Screen Shot 2022-05-30 at 12 30 43 PM" src="https://user-images.githubusercontent.com/2906673/171032193-3ed54f1e-e208-4585-b29a-f2a6aae2bb2f.png">

Maybe this is wrong?

I tried to replace the size with a different number. The error goes away but nothing renders. A lot of warnings are generated.

`em++ --version`
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0-git
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cwoffenden** [comment]
Hi! Your Emscripten version is too old. The underlying WebGPU API keeps changing so the only way to keep the C++ version sensibly working is to only support more recent versions. The 3.0.0 release is from November 2021, and there's been far too many changes to the WebGPU implementation in that time.

Does this prebuilt version work for you?

https://wip.numfum.com/2022-04-25/index.html

**Comment by gracicot** [comment]
Yes, the new emscripten is working, thank you very much.

I've not been able to package emscripten 3.1.9 using nix though, so I used emsdk.
