### ISSUE TITLE
Upgrade to latest Dawn

### ISSUE THREAD

**Issue by stefan-tb** [cwoffenden/hello-webgpu#7]
Hi Carl,

I am wondering if you would be open to bump up the used version of Dawn to latest? Since this would save me some days I am willing to **compensate** your efforts financially. I am an experienced DX11 dev but my Dawn prototyping is dragging on for to long, hence the question.

Please let me know if you could help me out.

Thank you very much.

**Comment by cwoffenden** [comment]
Hi there, Stefan. I started looking at this a few weeks ago, but stopped because Dawn latest wasn't building with MSVC again (in release, IIRC). I'll take a look again next week - no compensation necessary, I do this for our commercial engine at work anyway (and for pleasure, plus you couldn't afford me! 😉).

**Comment by stefan-tb** [comment]
Yeah, ive heard such rumors about Switzerland. :)

The update is highly appreciated. My state: I am halfway thru, latest Dawn compiles today and I managed to update most of your code to the new API. const buffer part is TODO but i am afraid that more stuff (shaders?) surfaces when this part works too.

Thanks!

**Comment by cwoffenden** [comment]
I'm reopening as a reminder and I will update the libs and sample next week.

(It's coming back to me now, Dawn for Windows was failing to link in one of the Depot Tools scripts in release. I recall previously solving something similar but I didn't update my notes.)

**Comment by stefan-tb** [comment]
Hi Carl,

one more update. I managed to get things working with dawn/latest. At least at Windows. A pull request probably is to much (since it highly likely breaks mac + wasm) but would you be interested into at least the modified main.cpp + webgpu.cpp? Dunno how to share them.

**Comment by cwoffenden** [comment]
Hi again, Stefan. I'd certainly be interest! You can email the cpp files, then I'll use them for testing, then after I create the platform libs you can create a PR with your changes if you like? Or I can just add them (if you create a PR you'll be in the list of contributors).

My mail address is my Github username at Gmail.

**Comment by stefan-tb** [comment]
Hi Carl, i don't know the notification thingy works in GutHub (its a primer for me) but i created a Pull Request with the changes. Let me know if you need any help or want me to change stuff.

**Comment by cwoffenden** [comment]
Hi, Stefan. I got the notification, and took a quick look. I should be able to look at it properly and merge later in the week.

**Comment by cwoffenden** [comment]
All Mac and Windows libs are up-to-date, Emscripten updated, tested on everything except Mac ARM (I'll test in the morning).

Thanks for you help!

**Comment by stefan-tb** [comment]
Has been a pleasure sir. 👍 And thanks for sharing the project in the first place! It really helped me to get started w/ cross-platform native webGPU.
